In [ ]:
import numpy as np

my_list = [1,2,3,4,5]
np.array(my_list)

my_matrix = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]

np.array(my_matrix)
np.arange(0,11)
np.zeros(5)
np.zeros((5,5))
np.linspace(0,10,5)
np.eye(2)
np.random.rand(2)
np.random.rand(5,5)
np.random.randn(5)
np.random.randint(1,100)
np.random.randint(1,100, 5)


array([87, 80,  3, 46, 81], dtype=int32)

In [62]:
# Array Attributes and Methods

import numpy as np

arr = np.arange(25)
arr.reshape(5,5)
arr.max()
arr.argmax
arr.shape
arr.dtype
# Broadcasting in arrays
arr[0:10] = 100
bool_arr = arr>10
gt_4 = arr[arr > 20]
arr2 = np.linspace(1,20, 5)
np.exp(arr2)
np.log(arr2)
np.sin(arr2)


array([ 0.84147098, -0.50827908, -0.87969576,  0.44212217,  0.91294525])

In [ ]:
# Broadcasting in arrays

import numpy as np

np_array1 = np.array([1,2,3,4,5,6,7])
np_array2 = np.array([12,243,5,7,21,45,24])
scalar = np_array + 2
addition = np_array1 + np_array2

np_array3 = np.array([[1],
                      [2],
                      [3]])

add2 = np_array3 + np_array1
add2

array([[ 2,  3,  4,  5,  6,  7,  8],
       [ 3,  4,  5,  6,  7,  8,  9],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [33]:
import numpy as np
import sympy as sy

my_matrix1 = np.array([[1, 2, 3],
                       [5, 6, 8],
                       [9, 1, 0]])
my_matrix2 = np.array([[12, 3, 76, 9],
                       [2, 4, 5, 8],
                       [12, 1, 10, 67]])

matrix = np.array([[1, 2],
                   [3, 4]])
# sum1 = my_matrix1 + my_matrix2
scalar = my_matrix1 * 2
# likewise_multiplication = my_matrix1 * my_matrix2
matrix_mult = my_matrix1 @ my_matrix2
matrix_mult = np.dot(my_matrix1, my_matrix2)
transpose = my_matrix1.T
determinant = np.linalg.det(matrix)
inverse = np.linalg.inv(matrix)

sy_matrix = sy.Matrix([[1, 2, 3],
                       [5, 6, 8],
                       [9, 1, 0]])

echelon = sy_matrix.echelon_form()
echelon

Matrix([
[1,  2,   3],
[0, -4,  -7],
[0,  0, -11]])